### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by tallal76** [tallal76/normayna#22]
Pensez à créer un répertoire admin pour tous les fichiers qui concernent la partie Admin du site.
Merci
Sonia

**Comment by tallal76** [comment]
Voici ce que je te propose, créer un répertoire admin et ajouter un répertoire pour chaque partie de l'admin c'est-à-dire 
- evenements
- produits
- connexion

**Comment by BouazziH** [comment]
ok bien reçu
